#!/Users/Amarsing/anaconda3/bin/python

# This file takes a string of DNA and returns the reverse complement

dna = "GGCTTACACGGGCCTGAAGCGTTTTCTAGGGAAACTAAGCAATGCGATCCCCTCGCGGTTATGAGCCTTGGCCAGCTACTAAGTTTACTGCTACAGGTGGCTCCAATGCTACCCAGACGAGAGCGCGGTTTAGGATTAGGTGTACCGCCTAGGACACATGTGCCACACGTAGTACGGGTAGCGTGGAGTAGCTTGGACATCTATCACTTGATATGCCAGCTCCAACCGACAGTTTATACTACTTGTCTAAATACCATGCTAGACAGGCTCACACTGCTCTTTCAGTCCAATATGTATATAGATTCCGTAAGGATGTGCATATCGGTTAGTCCTCACCAGTTCGTCGCTACTTTATTAGCTGTGTTCCATCAGAGGGGCAGATGATAAATGGGGCTTAACTAGTCGAATAAGAATAATTCATAGACAACTGGGCAAAGATCGCGAACCAAGCCTGCGATAACTTCCTTGGCGGCCTCTGACAGCAGCTGTAACAACCTTTAGGCCTTACTGCTAGTCTTCCGGTGCCCGTCTCCTGAGTCTCGTCTTCAGTTACCATGACGAGCTGATAAGGCTAATTAAACACCGCATTACACTTTCGGTGATTTAAGGGTTAACCATAAGTACCGAGCCATAGATGACAGTTTTGCGCGGACAGTGTAGCTATCGTTGTCGAGGTGCGCAGAGAGGCTGGACGGATTAGTGTTAACAGTTCGTTCAGTCAGATTTGTAACGAGATCATGATATGTAATTTCTATTCATAAATCAGTAACCTACGTCATCCTAAGAACACTGGCATAGCTCTAAAAAGGAGTCAGCTCGCGTTAATGCCAGCGAACCGTCTCGACCATCCGATAACTCCCCGCGCGACCACATTGGAATCCGGTCGATGCTAACTACAACGCTGCAGGGCCCAGCAGCCAGGTGGTAAAGCAGTTTGGTTTATTTTTGGAGAGAGAATCGATTATACGTACGTATACTCCA"


def reverse_string(seq):
    return seq[::-1]


def complement(seq):
    base_complement = {'A':'T', 'a':'t', 'T':'A', 't':'a', 'C':'G', 'c':'g', 'G':'C', 'g':'c', 'n':'n', 'N':'N'}
    seq2 = ''
    for base in seq:
        seq2 = seq2 + base_complement[base]
    return seq2


def reverse_complement(seq):
    seq = reverse_string(seq)
    seq = complement(seq)
    return seq

print(reverse_complement(dna))
